// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOpmfdMm7WgPWUM0ggl7Hrx1H-9kE579Q',
    appId: '1:624630192761:web:8654506d6b3a2e97e1d2a8',
    messagingSenderId: '624630192761',
    projectId: 'fir-analytics-c66d6',
    authDomain: 'fir-analytics-c66d6.firebaseapp.com',
    storageBucket: 'fir-analytics-c66d6.appspot.com',
    measurementId: 'G-MJ4ZDHSMBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArXM4VXNWXowh7v2vjSQV4pGI_Rc2WULo',
    appId: '1:624630192761:android:7e9fd6137dc00a0be1d2a8',
    messagingSenderId: '624630192761',
    projectId: 'fir-analytics-c66d6',
    storageBucket: 'fir-analytics-c66d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcG0d_4z4f0qZZOFALFjP8-IhWJ1XBOFE',
    appId: '1:624630192761:ios:787c9a10b11886e1e1d2a8',
    messagingSenderId: '624630192761',
    projectId: 'fir-analytics-c66d6',
    storageBucket: 'fir-analytics-c66d6.appspot.com',
    iosBundleId: 'com.example.analytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcG0d_4z4f0qZZOFALFjP8-IhWJ1XBOFE',
    appId: '1:624630192761:ios:787c9a10b11886e1e1d2a8',
    messagingSenderId: '624630192761',
    projectId: 'fir-analytics-c66d6',
    storageBucket: 'fir-analytics-c66d6.appspot.com',
    iosBundleId: 'com.example.analytics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOpmfdMm7WgPWUM0ggl7Hrx1H-9kE579Q',
    appId: '1:624630192761:web:99a7a5c2ef1d3047e1d2a8',
    messagingSenderId: '624630192761',
    projectId: 'fir-analytics-c66d6',
    authDomain: 'fir-analytics-c66d6.firebaseapp.com',
    storageBucket: 'fir-analytics-c66d6.appspot.com',
    measurementId: 'G-F8EE3LN72Q',
  );
}
